// Generates dist/_headers for Cloudflare Pages.
//
// The site ships two inline <script> blocks per page — the is:inline theme
// bootstrap (must stay inline to avoid a flash of the wrong theme) and Astro's
// bundled module script. Their contents change whenever the source does, so the
// CSP script-src hashes are computed here after `astro build` rather than being
// hand-maintained in public/_headers.

import { createHash } from "node:crypto";
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const DIST = fileURLToPath(new URL("../dist", import.meta.url));

/** Inline <script>…</script> blocks, i.e. those without a src attribute. */
const INLINE_SCRIPT = /<script(?![^>]*\ssrc=)([^>]*)>([\s\S]*?)<\/script>/gi;
const INLINE_STYLE = /<style([^>]*)>([\s\S]*?)<\/style>/gi;

function htmlFiles(dir) {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) return htmlFiles(path);
    return entry.isFile() && entry.name.endsWith(".html") ? [path] : [];
  });
}

function hash(source) {
  return `'sha256-${createHash("sha256").update(source, "utf8").digest("base64")}'`;
}

function collect(pattern, files) {
  const hashes = new Set();
  for (const file of files) {
    const html = readFileSync(file, "utf8");
    for (const [, , body] of html.matchAll(pattern)) hashes.add(hash(body));
  }
  return [...hashes].sort();
}

const files = htmlFiles(DIST);
if (files.length === 0) {
  throw new Error(`No HTML found in ${DIST} — run astro build first.`);
}

const scriptHashes = collect(INLINE_SCRIPT, files);
const styleHashes = collect(INLINE_STYLE, files);

const csp = [
  "default-src 'none'",
  ["script-src 'self'", ...scriptHashes].join(" "),
  ["style-src 'self'", ...styleHashes].join(" "),
  "img-src 'self' data:",
  "font-src 'self'",
  "connect-src 'self'",
  "manifest-src 'self'",
  "base-uri 'none'",
  "form-action 'none'",
  "frame-ancestors 'none'",
  "object-src 'none'",
  "upgrade-insecure-requests",
].join("; ");

// Every capability the site never uses, denied outright.
const permissionsPolicy = [
  "accelerometer",
  "autoplay",
  "browsing-topics",
  "camera",
  "display-capture",
  "encrypted-media",
  "fullscreen",
  "geolocation",
  "gyroscope",
  "magnetometer",
  "microphone",
  "midi",
  "payment",
  "publickey-credentials-get",
  "screen-wake-lock",
  "usb",
  "xr-spatial-tracking",
]
  .map((feature) => `${feature}=()`)
  .join(", ");

const headers = `# Generated by scripts/generate-headers.mjs — do not edit by hand.
# Cloudflare Pages reads this file from the root of the deployed directory.
/*
  Content-Security-Policy: ${csp}
  Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
  X-Frame-Options: DENY
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: ${permissionsPolicy}
  Cross-Origin-Opener-Policy: same-origin
  Cross-Origin-Resource-Policy: same-origin
  X-Permitted-Cross-Domain-Policies: none
`;

writeFileSync(join(DIST, "_headers"), headers);
console.log(
  `_headers written: ${scriptHashes.length} inline script hash(es), ` +
    `${styleHashes.length} inline style hash(es), across ${files.length} page(s).`,
);
